.TH "/Users/halsi/Desktop/Uni/Betriebssysteme/Betriebssysteme1/cmake-build-debug/CMakeFiles/3.17.5/CompilerIdC Directory Reference" 3 "Sat Apr 17 2021" "Betriebssysteme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/halsi/Desktop/Uni/Betriebssysteme/Betriebssysteme1/cmake-build-debug/CMakeFiles/3.17.5/CompilerIdC Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCMakeCCompilerId\&.c\fP"
.br
.in -1c
