.TH "md__r_e_a_d_m_e" 3 "Sat Apr 17 2021" "Betriebssysteme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Pthread Demo auf Basis von Posix Threads 
Enthalten: Makefile CLion Projekt CI Beispiel
.PP
Hinweis zu CI/CD
.PP
Für die Methodik 'Continuous Integration (CI)' gibt es drei Hauptansätze, die jeweils entsprechend Ihrer Strategie angewendet werden können:
.PP
Continuous Integration (CI), Continuous Delivery und Continuous Deployment\&. Eine Übersicht finden Sie in der Einführung in CI / CD mit GitLab\&.
.PP
https://docs.gitlab.com/ee/ci/ 
