.TH "OSMPLib.c" 3 "Sat Apr 17 2021" "Betriebssysteme" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OSMPLib.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'OSMPLib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Betriebssysteme from the source code\&.
